server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;

    location /health {
        proxy_pass http://api:8080/health;
    }

    location /ready {
        proxy_pass http://api:8080/ready;
    }

    location /v1/ {
        proxy_pass http://api:8080/v1/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
